### ISSUE TITLE
Uncaught (in promise) TypeError: e.data.forEach is not a function     at grapesjs_save.min.js:18:50148

### ISSUE THREAD

**Issue by treborin** [Diether14/grapesjs-save#5]
Hi there,
Thanks for sharing this nice grapesjs db save test.

Everything works ok using GrapesJS version  0.15.9, except the initial table. No pages show at all.
When you add a new one, in this case, it is listed, but if you refresh, nothing there.

It seems to me it is the way the forEach uses data. Instead of as an objet, it treat it as an array, but can't solve this.
Could you help me?
Thanks
